In [1]:
import pandas as pd
import numpy as np

In [2]:
customers = pd.read_csv("customers.csv")
products = pd.read_csv("products.csv")
orders = pd.read_csv("orders.csv")

In [3]:
print("Customers Shape:", customers.shape)
print("Products Shape:", products.shape)
print("Orders Shape:", orders.shape)

Customers Shape: (21, 7)
Products Shape: (16, 6)
Orders Shape: (51, 8)

In [4]:
print("Customers Columns:")
print(customers.columns)

print("\nProducts Columns:")
print(products.columns)

print("\nOrders Columns:")
print(orders.columns)

Customers Columns:
Index(['customer_id', 'customer_name', 'email', 'city', 'age', 'gender',
       'signup_date'],
      dtype='str')

Products Columns:
Index(['product_id', 'product_name', 'category', 'price', 'stock_quantity',
       'rating'],
      dtype='str')

Orders Columns:
Index(['order_id', 'customer_id', 'product_id', 'quantity', 'discount',
       'order_date', 'payment_method', 'order_status'],
      dtype='str')

In [5]:
print("Customers Data Types:")
print(customers.dtypes)

print("\nProducts Data Types:")
print(products.dtypes)

print("\nOrders Data Types:")
print(orders.dtypes)

Customers Data Types:
customer_id        str
customer_name      str
email              str
city               str
age              int64
gender             str
signup_date        str
dtype: object

Products Data Types:
product_id            str
product_name          str
category              str
price             float64
stock_quantity      int64
rating            float64
dtype: object

Orders Data Types:
order_id            str
customer_id         str
product_id          str
quantity          int64
discount          int64
order_date          str
payment_method      str
order_status        str
dtype: object

In [6]:
print("Customers Missing Values:")
print(customers.isnull().sum())

print("\nProducts Missing Values:")
print(products.isnull().sum())

print("\nOrders Missing Values:")
print(orders.isnull().sum())

Customers Missing Values:
customer_id      0
customer_name    0
email            1
city             0
age              0
gender           0
signup_date      0
dtype: int64

Products Missing Values:
product_id        0
product_name      0
category          0
price             1
stock_quantity    0
rating            0
dtype: int64

Orders Missing Values:
order_id          0
customer_id       0
product_id        0
quantity          0
discount          0
order_date        0
payment_method    1
order_status      0
dtype: int64

In [7]:
print("Customers Duplicate Rows:", customers.duplicated().sum())
print("Products Duplicate Rows:", products.duplicated().sum())
print("Orders Duplicate Rows:", orders.duplicated().sum())

Customers Duplicate Rows: 1
Products Duplicate Rows: 1
Orders Duplicate Rows: 1

In [8]:
customers = customers.drop_duplicates()
products = products.drop_duplicates()
orders = orders.drop_duplicates()

In [9]:
print("Customers Duplicate Rows:", customers.duplicated().sum())
print("Products Duplicate Rows:", products.duplicated().sum())
print("Orders Duplicate Rows:", orders.duplicated().sum())

Customers Duplicate Rows: 0
Products Duplicate Rows: 0
Orders Duplicate Rows: 0

In [10]:
print("Customers Missing Email:")
print(customers[customers["email"].isnull()])

print("\nProducts Missing Price:")
print(products[products["price"].isnull()])

print("\nOrders Missing Payment Method:")
print(orders[orders["payment_method"].isnull()])

Customers Missing Email:
  customer_id       customer_name email   city  age gender signup_date
3     CUST004  Ehsaan Chakraborty   NaN  Surat   52   Male  2025-01-22

Products Missing Price:
  product_id  product_name   category  price  stock_quantity  rating
4    PROD005  Office Chair  Furniture    NaN              87     2.7

Orders Missing Payment Method:
   order_id customer_id product_id  quantity  discount  order_date  \
10   ORD011     CUST006    PROD012         4        20  2026-03-03

   payment_method order_status
10            NaN    Delivered

In [11]:
print(products)

   product_id       product_name     category    price  stock_quantity  rating
0     PROD001     Wireless Mouse  Electronics  3357.13              42     5.0
1     PROD002  Bluetooth Speaker  Electronics  4298.29              17     3.5
2     PROD003    Gaming Keyboard  Electronics  2349.04              51     2.9
3     PROD004           Notebook   Stationery  1873.06              90     3.2
4     PROD005       Office Chair    Furniture      NaN              87     2.7
5     PROD006       Water Bottle    Lifestyle  3229.64              73     4.3
6     PROD007       Laptop Stand  Electronics   942.50              53     3.2
7     PROD008           Pen Pack   Stationery  4638.15              93     3.9
8     PROD009        Smart Watch  Electronics  3470.38              12     3.1
9     PROD010           Backpack    Lifestyle   305.69              45     3.5
10    PROD011           LED Lamp         Home   471.01              77     4.7
11    PROD012          USB Cable  Electronics  1676.19              88     3.7
12    PROD013         Coffee Mug         Home  4440.71              87     3.6
13    PROD014        Study Table    Furniture  1434.67              36     4.4
14    PROD015         Power Bank  Electronics  2764.04             100     4.0

In [12]:
# Handle missing email
customers["email"] = customers["email"].fillna("Not Available")

# Handle missing price using median
products["price"] = products["price"].fillna(products["price"].median())

# Handle missing payment method
orders["payment_method"] = orders["payment_method"].fillna("Unknown")

In [13]:
print("Customers Missing Values:")
print(customers.isnull().sum())

print("\nProducts Missing Values:")
print(products.isnull().sum())

print("\nOrders Missing Values:")
print(orders.isnull().sum())

Customers Missing Values:
customer_id      0
customer_name    0
email            0
city             0
age              0
gender           0
signup_date      0
dtype: int64

Products Missing Values:
product_id        0
product_name      0
category          0
price             0
stock_quantity    0
rating            0
dtype: int64

Orders Missing Values:
order_id          0
customer_id       0
product_id        0
quantity          0
discount          0
order_date        0
payment_method    0
order_status      0
dtype: int64

In [14]:
# Customers
customers["customer_name"] = customers["customer_name"].str.strip().str.title()
customers["email"] = customers["email"].str.strip()
customers["city"] = customers["city"].str.strip().str.title()
customers["gender"] = customers["gender"].str.strip().str.title()

# Products
products["product_name"] = products["product_name"].str.strip().str.title()
products["category"] = products["category"].str.strip().str.title()

# Orders
orders["payment_method"] = orders["payment_method"].str.strip().str.title()
orders["order_status"] = orders["order_status"].str.strip().str.title()

In [15]:
print("Customers:")
display(customers.head())

print("Products:")
display(products.head())

print("Orders:")
display(orders.head())

Customers:

,customer_id,customer_name,email,city,age,gender,signup_date
0,CUST001,Shamik Dutt,bhatiavritika@hotmail.com,Surat,25,Male,2023-12-29
1,CUST002,Anvi Chacko,sachdevkimaya@gmail.com,Surat,35,Male,2026-01-08
2,CUST003,Vivaan Saha,ukhurana@hotmail.com,Mumbai,26,Male,2024-09-05
3,CUST004,Ehsaan Chakraborty,Not Available,Surat,52,Male,2025-01-22
4,CUST005,Indrans Mammen,settyabram@agrawal.info,Bangalore,45,Male,2023-10-29

Products:

  product_id       product_name     category    price  stock_quantity  rating
0    PROD001     Wireless Mouse  Electronics  3357.13              42     5.0
1    PROD002  Bluetooth Speaker  Electronics  4298.29              17     3.5
2    PROD003    Gaming Keyboard  Electronics  2349.04              51     2.9
3    PROD004           Notebook   Stationery  1873.06              90     3.2
4    PROD005       Office Chair    Furniture  2556.54              87     2.7

Orders:

,order_id,customer_id,product_id,quantity,discount,order_date,payment_method,order_status
0,ORD001,CUST013,PROD012,2,5,2026-04-19,Cash On Delivery,Delivered
1,ORD002,CUST004,PROD005,2,15,2025-12-03,Upi,Shipped
2,ORD003,CUST020,PROD015,5,10,2026-02-26,Upi,Delivered
3,ORD004,CUST018,PROD009,3,0,2026-05-14,Debit Card,Shipped
4,ORD005,CUST015,PROD001,3,20,2025-12-31,Credit Card,Delivered

In [16]:
print("Customers Info:")
customers.info()

print("\nProducts Info:")
products.info()

print("\nOrders Info:")
orders.info()

Customers Info:
<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   customer_id    20 non-null     str
 1   customer_name  20 non-null     str
 2   email          20 non-null     str
 3   city           20 non-null     str
 4   age            20 non-null     int64
 5   gender         20 non-null     str
 6   signup_date    20 non-null     str
dtypes: int64(1), str(6)
memory usage: 1.2 KB

Products Info:
<class 'pandas.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      15 non-null     str
 1   product_name    15 non-null     str
 2   category        15 non-null     str
 3   price           15 non-null     float64
 4   stock_quantity  15 non-null     int64
 5   rating          15 non-null     float64
dtypes: float64(2), int64(1), str(3)
memory usage: 852.0 bytes

Orders Info:
<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   order_id        50 non-null     str
 1   customer_id     50 non-null     str
 2   product_id      50 non-null     str
 3   quantity        50 non-null     int64
 4   discount        50 non-null     int64
 5   order_date      50 non-null     str
 6   payment_method  50 non-null     str
 7   order_status    50 non-null     str
dtypes: int64(2), str(6)
memory usage: 3.3 KB

In [17]:
# Save cleaned datasets

customers.to_csv("customers_cleaned.csv", index=False)
products.to_csv("products_cleaned.csv", index=False)
orders.to_csv("orders_cleaned.csv", index=False)

print("Cleaned datasets saved successfully!")

Cleaned datasets saved successfully!

In [18]:


print("Customers - Average Age:", np.mean(customers["age"].to_numpy()))

print("Products - Average Price:", np.mean(products["price"].to_numpy()))
print("Products - Average Stock Quantity:", np.mean(products["stock_quantity"].to_numpy()))
print("Products - Average Rating:", np.mean(products["rating"].to_numpy()))

print("Orders - Average Quantity:", np.mean(orders["quantity"].to_numpy()))
print("Orders - Average Discount:", np.mean(orders["discount"].to_numpy()))

Customers - Average Age: 35.2
Products - Average Price: 2520.469333333333
Products - Average Stock Quantity: 63.4
Products - Average Rating: 3.7133333333333334
Orders - Average Quantity: 3.06
Orders - Average Discount: 10.3

In [19]:
# Median of numeric columns

print("Customers - Median Age:", np.median(customers["age"].to_numpy()))

print("Products - Median Price:", np.median(products["price"].to_numpy()))
print("Products - Median Stock Quantity:", np.median(products["stock_quantity"].to_numpy()))
print("Products - Median Rating:", np.median(products["rating"].to_numpy()))

print("Orders - Median Quantity:", np.median(orders["quantity"].to_numpy()))
print("Orders - Median Discount:", np.median(orders["discount"].to_numpy()))

Customers - Median Age: 37.0
Products - Median Price: 2556.54
Products - Median Stock Quantity: 73.0
Products - Median Rating: 3.6
Orders - Median Quantity: 3.0
Orders - Median Discount: 10.0

In [20]:
# Standard deviation of numeric columns

print("Customers - Standard Deviation of Age:",
      np.std(customers["age"].to_numpy()))

print("Products - Standard Deviation of Price:",
      np.std(products["price"].to_numpy()))

print("Products - Standard Deviation of Stock Quantity:",
      np.std(products["stock_quantity"].to_numpy()))

print("Products - Standard Deviation of Rating:",
      np.std(products["rating"].to_numpy()))

print("Orders - Standard Deviation of Quantity:",
      np.std(orders["quantity"].to_numpy()))

print("Orders - Standard Deviation of Discount:",
      np.std(orders["discount"].to_numpy()))

Customers - Standard Deviation of Age: 11.13822247937255
Products - Standard Deviation of Price: 1352.3864587484682
Products - Standard Deviation of Stock Quantity: 27.71714270988263
Products - Standard Deviation of Rating: 0.6458758050550861
Orders - Standard Deviation of Quantity: 1.302459212413195
Orders - Standard Deviation of Discount: 7.576938695805846

In [21]:
# Minimum and Maximum of numeric columns

print("Customers - Minimum Age:", np.min(customers["age"].to_numpy()))
print("Customers - Maximum Age:", np.max(customers["age"].to_numpy()))

print("Products - Minimum Price:", np.min(products["price"].to_numpy()))
print("Products - Maximum Price:", np.max(products["price"].to_numpy()))

print("Products - Minimum Stock Quantity:", np.min(products["stock_quantity"].to_numpy()))
print("Products - Maximum Stock Quantity:", np.max(products["stock_quantity"].to_numpy()))

print("Products - Minimum Rating:", np.min(products["rating"].to_numpy()))
print("Products - Maximum Rating:", np.max(products["rating"].to_numpy()))

print("Orders - Minimum Quantity:", np.min(orders["quantity"].to_numpy()))
print("Orders - Maximum Quantity:", np.max(orders["quantity"].to_numpy()))

print("Orders - Minimum Discount:", np.min(orders["discount"].to_numpy()))
print("Orders - Maximum Discount:", np.max(orders["discount"].to_numpy()))

Customers - Minimum Age: 18
Customers - Maximum Age: 53
Products - Minimum Price: 305.69
Products - Maximum Price: 4638.15
Products - Minimum Stock Quantity: 12
Products - Maximum Stock Quantity: 100
Products - Minimum Rating: 2.7
Products - Maximum Rating: 5.0
Orders - Minimum Quantity: 1
Orders - Maximum Quantity: 5
Orders - Minimum Discount: 0
Orders - Maximum Discount: 20

In [22]:
# Reshape example

numbers = np.array([1, 2, 3, 4, 5, 6])

reshaped_array = numbers.reshape(2, 3)

print("Original Array:")
print(numbers)

print("\nReshaped Array:")
print(reshaped_array)

Original Array:
[1 2 3 4 5 6]

Reshaped Array:
[[1 2 3]
 [4 5 6]]

In [23]:
# Flatten example

flattened_array = reshaped_array.flatten()

print("Reshaped Array:")
print(reshaped_array)

print("\nFlattened Array:")
print(flattened_array)

Reshaped Array:
[[1 2 3]
 [4 5 6]]

Flattened Array:
[1 2 3 4 5 6]

In [24]:
# Transpose example

transposed_array = reshaped_array.transpose()

print("Original Reshaped Array:")
print(reshaped_array)

print("\nTransposed Array:")
print(transposed_array)

Original Reshaped Array:
[[1 2 3]
 [4 5 6]]

Transposed Array:
[[1 4]
 [2 5]
 [3 6]]

In [25]:
# Boolean masking example

numbers = np.array([1, 2, 3, 4, 5, 6])

mask = numbers > 3

print("Boolean Mask:")
print(mask)

print("\nValues greater than 3:")
print(numbers[mask])

Boolean Mask:
[False False False  True  True  True]

Values greater than 3:
[4 5 6]

In [26]:
# Fancy indexing example

numbers = np.array([10, 20, 30, 40, 50, 60])

selected_values = numbers[[0, 2, 5]]

print("Original Array:")
print(numbers)

print("\nSelected Values:")
print(selected_values)

Original Array:
[10 20 30 40 50 60]

Selected Values:
[10 30 60]

In [27]:
# Matrix multiplication example

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

result = np.matmul(A, B)

print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

print("\nMatrix Multiplication Result:")
print(result)

Matrix A:
[[1 2]
 [3 4]]

Matrix B:
[[5 6]
 [7 8]]

Matrix Multiplication Result:
[[19 22]
 [43 50]]

In [28]:
# Merge orders with products to get product price

orders_with_price = orders.merge(
    products[["product_id", "price"]],
    on="product_id",
    how="left"
)

# Calculate total price for each order
orders_with_price["total_price"] = (
    orders_with_price["quantity"] * orders_with_price["price"]
)

# Calculate total spending for each customer
customer_spending = (
    orders_with_price.groupby("customer_id")["total_price"]
    .sum()
)

# Get top 5 customers
top_5_customers = customer_spending.sort_values(
    ascending=False
).head(5)

print("Top 5 Customers by Total Spending:")
print(top_5_customers)

Top 5 Customers by Total Spending:
customer_id
CUST002    44332.11
CUST004    40277.46
CUST014    33159.31
CUST006    28323.89
CUST003    26963.97
Name: total_price, dtype: float64

In [29]:
# Find the most sold product

product_sales = (
    orders.groupby("product_id")["quantity"]
    .sum()
    .sort_values(ascending=False)
)

most_sold_product = product_sales.head(1)

print("Most Sold Product:")
print(most_sold_product)

Most Sold Product:
product_id
PROD007    22
Name: quantity, dtype: int64

In [30]:
# Merge orders with products to get category and price

orders_with_product = orders.merge(
    products[["product_id", "category", "price"]],
    on="product_id",
    how="left"
)

# Calculate revenue for each order
orders_with_product["revenue"] = (
    orders_with_product["quantity"] * orders_with_product["price"]
)

# Calculate total revenue by category
category_revenue = (
    orders_with_product.groupby("category")["revenue"]
    .sum()
    .sort_values(ascending=False)
)

print("Revenue by Category:")
print(category_revenue)

print("\nHighest Revenue Category:")
print(category_revenue.head(1))

Revenue by Category:
category
Electronics    183424.28
Stationery      77153.49
Furniture       49825.46
Home            34853.05
Lifestyle       19205.10
Name: revenue, dtype: float64

Highest Revenue Category:
category
Electronics    183424.28
Name: revenue, dtype: float64

In [31]:
# Calculate average order quantity

average_order_quantity = orders["quantity"].mean()

print("Average Order Quantity:", average_order_quantity)

Average Order Quantity: 3.06

In [32]:
# Find the city with the most customers

city_customer_count = (
    customers.groupby("city")["customer_id"]
    .count()
    .sort_values(ascending=False)
)

print("Customers by City:")
print(city_customer_count)

print("\nCity with Most Customers:")
print(city_customer_count.head(1))

Customers by City:
city
Surat        5
Jaipur       4
Bangalore    3
Ahmedabad    3
Mumbai       3
Delhi        2
Name: customer_id, dtype: int64

City with Most Customers:
city
Surat    5
Name: customer_id, dtype: int64

In [33]:
# Create Total Price column

orders_with_product["total_price"] = (
    orders_with_product["quantity"] * orders_with_product["price"]
)

print(orders_with_product[[
    "order_id",
    "product_id",
    "quantity",
    "price",
    "total_price"
]].head())

  order_id product_id  quantity    price  total_price
0   ORD001    PROD012         2  1676.19      3352.38
1   ORD002    PROD005         2  2556.54      5113.08
2   ORD003    PROD015         5  2764.04     13820.20
3   ORD004    PROD009         3  3470.38     10411.14
4   ORD005    PROD001         3  3357.13     10071.39

In [34]:
# Create Discounted Price column

orders_with_product["discounted_price"] = (
    orders_with_product["total_price"]
    * (1 - orders_with_product["discount"] / 100)
)

print(orders_with_product[[
    "order_id",
    "quantity",
    "price",
    "discount",
    "total_price",
    "discounted_price"
]].head())

  order_id  quantity    price  discount  total_price  discounted_price
0   ORD001         2  1676.19         5      3352.38          3184.761
1   ORD002         2  2556.54        15      5113.08          4346.118
2   ORD003         5  2764.04        10     13820.20         12438.180
3   ORD004         3  3470.38         0     10411.14         10411.140
4   ORD005         3  3357.13        20     10071.39          8057.112

In [35]:
# Calculate product-wise sales

product_wise_sales = (
    orders.groupby("product_id")["quantity"]
    .sum()
    .sort_values(ascending=False)
)

print("Product-wise Sales:")
print(product_wise_sales)

Product-wise Sales:
product_id
PROD007    22
PROD003    17
PROD005    15
PROD008    13
PROD009    12
PROD010    10
PROD004     9
PROD001     9
PROD011     8
PROD014     8
PROD013     7
PROD015     7
PROD012     6
PROD006     5
PROD002     5
Name: quantity, dtype: int64

In [36]:
# Calculate customer-wise spending

customer_wise_spending = (
    orders_with_product.groupby("customer_id")["total_price"]
    .sum()
    .sort_values(ascending=False)
)

print("Customer-wise Spending:")
print(customer_wise_spending)

Customer-wise Spending:
customer_id
CUST002    44332.11
CUST004    40277.46
CUST014    33159.31
CUST006    28323.89
CUST003    26963.97
CUST012    26901.63
CUST013    24903.52
CUST008    23377.06
CUST005    19835.63
CUST018    17052.67
CUST020    16689.54
CUST017    13914.45
CUST015    11944.45
CUST010     9016.51
CUST019     6111.11
CUST009     5528.08
CUST007     5323.88
CUST001     4687.07
CUST016     3770.00
CUST011     2349.04
Name: total_price, dtype: float64

In [37]:
# Convert order_date to datetime

orders_with_product["order_date"] = pd.to_datetime(
    orders_with_product["order_date"]
)

# Extract month

orders_with_product["month"] = (
    orders_with_product["order_date"].dt.to_period("M")
)

# Calculate monthly sales

monthly_sales = (
    orders_with_product.groupby("month")["total_price"]
    .sum()
)

print("Monthly Sales:")
print(monthly_sales)

Monthly Sales:
month
2025-11     24351.16
2025-12     90369.21
2026-01    117234.82
2026-02     28253.20
2026-03     70101.32
2026-04     16070.91
2026-05     18080.76
Freq: M, Name: total_price, dtype: float64

In [38]:
# Filter orders with discount greater than 10%

high_discount_orders = orders[orders["discount"] > 10]

print("Orders with Discount Greater Than 10%:")
print(high_discount_orders)

Orders with Discount Greater Than 10%:
   order_id customer_id product_id  quantity  discount  order_date  \
1    ORD002     CUST004    PROD005         2        15  2025-12-03
4    ORD005     CUST015    PROD001         3        20  2025-12-31
8    ORD009     CUST018    PROD005         2        15  2025-12-08
9    ORD010     CUST020    PROD014         2        20  2026-04-05
10   ORD011     CUST006    PROD012         4        20  2026-03-03
13   ORD014     CUST017    PROD008         3        15  2025-12-09
14   ORD015     CUST019    PROD003         2        15  2026-04-16
15   ORD016     CUST004    PROD014         3        15  2025-12-15
16   ORD017     CUST006    PROD004         1        15  2025-12-04
17   ORD018     CUST007    PROD007         5        15  2026-01-23
23   ORD024     CUST002    PROD003         5        20  2025-12-05
24   ORD025     CUST003    PROD006         1        20  2026-03-31
25   ORD026     CUST004    PROD008         5        20  2026-03-04
27   ORD028     CUST013    PROD005         3        15  2026-01-27
28   ORD029     CUST015    PROD004         1        20  2025-11-23
30   ORD031     CUST018    PROD010         5        20  2026-03-13
34   ORD035     CUST005    PROD009         2        15  2026-02-14
37   ORD038     CUST008    PROD004         3        20  2026-01-13
44   ORD045     CUST014    PROD004         4        20  2026-02-09
45   ORD046     CUST014    PROD001         5        20  2025-12-02
47   ORD048     CUST010    PROD014         3        15  2026-03-30
48   ORD049     CUST014    PROD013         2        20  2026-01-09

      payment_method order_status
1                Upi      Shipped
4        Credit Card    Delivered
8        Credit Card    Cancelled
9        Credit Card    Cancelled
10           Unknown    Delivered
13       Credit Card      Pending
14  Cash On Delivery      Pending
15  Cash On Delivery      Shipped
16        Debit Card    Delivered
17       Credit Card      Shipped
23       Credit Card    Delivered
24               Upi      Pending
25               Upi    Delivered
27        Debit Card    Delivered
28       Credit Card    Cancelled
30               Upi    Cancelled
34  Cash On Delivery    Delivered
37  Cash On Delivery      Pending
44       Credit Card    Cancelled
45       Credit Card    Cancelled
47        Debit Card      Pending
48        Debit Card      Shipped

In [39]:
# Filter only delivered orders

delivered_orders = orders[orders["order_status"] == "Delivered"]

print("Delivered Orders:")
print(delivered_orders)

Delivered Orders:
   order_id customer_id product_id  quantity  discount  order_date  \
0    ORD001     CUST013    PROD012         2         5  2026-04-19
2    ORD003     CUST020    PROD015         5        10  2026-02-26
4    ORD005     CUST015    PROD001         3        20  2025-12-31
5    ORD006     CUST010    PROD007         2        10  2026-04-30
10   ORD011     CUST006    PROD012         4        20  2026-03-03
16   ORD017     CUST006    PROD004         1        15  2025-12-04
18   ORD019     CUST009    PROD015         2         0  2026-01-06
23   ORD024     CUST002    PROD003         5        20  2025-12-05
25   ORD026     CUST004    PROD008         5        20  2026-03-04
27   ORD028     CUST013    PROD005         3        15  2026-01-27
33   ORD034     CUST002    PROD003         4        10  2026-01-24
34   ORD035     CUST005    PROD009         2        15  2026-02-14
39   ORD040     CUST008    PROD009         2         0  2026-03-06
41   ORD042     CUST001    PROD007         4        10  2026-01-17
42   ORD043     CUST012    PROD013         5        10  2026-01-31

      payment_method order_status
0   Cash On Delivery    Delivered
2                Upi    Delivered
4        Credit Card    Delivered
5        Credit Card    Delivered
10           Unknown    Delivered
16        Debit Card    Delivered
18  Cash On Delivery    Delivered
23       Credit Card    Delivered
25               Upi    Delivered
27        Debit Card    Delivered
33               Upi    Delivered
34  Cash On Delivery    Delivered
39  Cash On Delivery    Delivered
41        Debit Card    Delivered
42               Upi    Delivered

In [40]:
# Filter customers from Ahmedabad

ahmedabad_customers = customers[
    customers["city"].str.strip().str.lower() == "ahmedabad"
]

print("Ahmedabad Customers:")
print(ahmedabad_customers)

Ahmedabad Customers:
   customer_id customer_name                     email       city  age  \
5      CUST006  Dhruv Kurian   sarrafgatik@hotmail.com  Ahmedabad   23
13     CUST014   Kashvi Kala  hazelchaudhry@gulati.com  Ahmedabad   42
17     CUST018    Oorja Kari           ibail@ratta.net  Ahmedabad   53

    gender signup_date
5     Male  2024-05-24
13    Male  2025-04-18
17  Female  2024-11-25

In [41]:
# Sort customers by highest total spending

sorted_customers = customer_wise_spending.sort_values(ascending=False)

print("Customers Sorted by Highest Spending:")
print(sorted_customers)

Customers Sorted by Highest Spending:
customer_id
CUST002    44332.11
CUST004    40277.46
CUST014    33159.31
CUST006    28323.89
CUST003    26963.97
CUST012    26901.63
CUST013    24903.52
CUST008    23377.06
CUST005    19835.63
CUST018    17052.67
CUST020    16689.54
CUST017    13914.45
CUST015    11944.45
CUST010     9016.51
CUST019     6111.11
CUST009     5528.08
CUST007     5323.88
CUST001     4687.07
CUST016     3770.00
CUST011     2349.04
Name: total_price, dtype: float64

In [42]:
# Sort products by highest price

most_expensive_products = products.sort_values(
    by="price",
    ascending=False
)

print("Most Expensive Products:")
print(most_expensive_products[[
    "product_id",
    "product_name",
    "category",
    "price"
]])

Most Expensive Products:
   product_id       product_name     category    price
7     PROD008           Pen Pack   Stationery  4638.15
12    PROD013         Coffee Mug         Home  4440.71
1     PROD002  Bluetooth Speaker  Electronics  4298.29
8     PROD009        Smart Watch  Electronics  3470.38
0     PROD001     Wireless Mouse  Electronics  3357.13
5     PROD006       Water Bottle    Lifestyle  3229.64
14    PROD015         Power Bank  Electronics  2764.04
4     PROD005       Office Chair    Furniture  2556.54
2     PROD003    Gaming Keyboard  Electronics  2349.04
3     PROD004           Notebook   Stationery  1873.06
11    PROD012          Usb Cable  Electronics  1676.19
13    PROD014        Study Table    Furniture  1434.67
6     PROD007       Laptop Stand  Electronics   942.50
10    PROD011           Led Lamp         Home   471.01
9     PROD010           Backpack    Lifestyle   305.69

In [43]:
# Convert customer names to uppercase

customers["customer_name_upper"] = customers["customer_name"].str.upper()

print("Customer Names in Uppercase:")
print(customers[["customer_name", "customer_name_upper"]])

Customer Names in Uppercase:
         customer_name customer_name_upper
0          Shamik Dutt         SHAMIK DUTT
1          Anvi Chacko         ANVI CHACKO
2          Vivaan Saha         VIVAAN SAHA
3   Ehsaan Chakraborty  EHSAAN CHAKRABORTY
4       Indrans Mammen      INDRANS MAMMEN
5         Dhruv Kurian        DHRUV KURIAN
6        Purab Mallick       PURAB MALLICK
7           Badal Shah          BADAL SHAH
8         Aaryahi Dass        AARYAHI DASS
9       Ryan Varughese      RYAN VARUGHESE
10         Nitya Baral         NITYA BARAL
11    Aayush Ramaswamy    AAYUSH RAMASWAMY
12          Riaan Hora          RIAAN HORA
13         Kashvi Kala         KASHVI KALA
14   Ivana Ranganathan   IVANA RANGANATHAN
15       Devansh Comar       DEVANSH COMAR
16        Dhruv Sarkar        DHRUV SARKAR
17          Oorja Kari          OORJA KARI
18        Rania Sharaf        RANIA SHARAF
19         Rohan Ghosh         ROHAN GHOSH

In [44]:
# Convert order_date to datetime format

orders["order_date"] = pd.to_datetime(orders["order_date"])

# Extract month, year and weekday
orders["month"] = orders["order_date"].dt.month
orders["year"] = orders["order_date"].dt.year
orders["weekday"] = orders["order_date"].dt.day_name()

print("Order Date with Month, Year and Weekday:")
print(orders[[
    "order_date",
    "month",
    "year",
    "weekday"
]])

Order Date with Month, Year and Weekday:
   order_date  month  year    weekday
0  2026-04-19      4  2026     Sunday
1  2025-12-03     12  2025  Wednesday
2  2026-02-26      2  2026   Thursday
3  2026-05-14      5  2026   Thursday
4  2025-12-31     12  2025  Wednesday
5  2026-04-30      4  2026   Thursday
6  2026-04-23      4  2026   Thursday
7  2026-01-21      1  2026  Wednesday
8  2025-12-08     12  2025     Monday
9  2026-04-05      4  2026     Sunday
10 2026-03-03      3  2026    Tuesday
11 2026-01-23      1  2026     Friday
12 2025-11-22     11  2025   Saturday
13 2025-12-09     12  2025    Tuesday
14 2026-04-16      4  2026   Thursday
15 2025-12-15     12  2025     Monday
16 2025-12-04     12  2025   Thursday
17 2026-01-23      1  2026     Friday
18 2026-01-06      1  2026    Tuesday
19 2025-12-03     12  2025  Wednesday
20 2026-03-25      3  2026  Wednesday
21 2025-11-21     11  2025     Friday
22 2025-12-30     12  2025    Tuesday
23 2025-12-05     12  2025     Friday
24 2026-03-31      3  2026    Tuesday
25 2026-03-04      3  2026  Wednesday
26 2026-03-08      3  2026     Sunday
27 2026-01-27      1  2026    Tuesday
28 2025-11-23     11  2025     Sunday
29 2025-12-24     12  2025  Wednesday
30 2026-03-13      3  2026     Friday
31 2026-05-09      5  2026   Saturday
32 2026-01-29      1  2026   Thursday
33 2026-01-24      1  2026   Saturday
34 2026-02-14      2  2026   Saturday
35 2025-12-19     12  2025     Friday
36 2026-03-11      3  2026  Wednesday
37 2026-01-13      1  2026    Tuesday
38 2026-01-20      1  2026    Tuesday
39 2026-03-06      3  2026     Friday
40 2026-03-21      3  2026   Saturday
41 2026-01-17      1  2026   Saturday
42 2026-01-31      1  2026   Saturday
43 2026-01-26      1  2026     Monday
44 2026-02-09      2  2026     Monday
45 2025-12-02     12  2025    Tuesday
46 2026-03-11      3  2026  Wednesday
47 2026-03-30      3  2026     Monday
48 2026-01-09      1  2026     Friday
49 2026-04-10      4  2026     Friday

In [45]:
# Final Business Insights

print("===== BUSINESS INSIGHTS =====")

print("1. Top Customer by Total Spending:")
print(top_5_customers.head(1))

print("\n2. Most Sold Product:")
print(most_sold_product)

print("\n3. Highest Revenue Category:")
print(category_revenue.head(1))

print("\n4. Average Order Quantity:")
print(average_order_quantity)

print("\n5. City with Most Customers:")
print(city_customer_count.head(1))

print("\n6. Highest Monthly Sales:")
print(monthly_sales.sort_values(ascending=False).head(1))

===== BUSINESS INSIGHTS =====
1. Top Customer by Total Spending:
customer_id
CUST002    44332.11
Name: total_price, dtype: float64

2. Most Sold Product:
product_id
PROD007    22
Name: quantity, dtype: int64

3. Highest Revenue Category:
category
Electronics    183424.28
Name: revenue, dtype: float64

4. Average Order Quantity:
3.06

5. City with Most Customers:
city
Surat    5
Name: customer_id, dtype: int64

6. Highest Monthly Sales:
month
2026-01    117234.82
Freq: M, Name: total_price, dtype: float64